#class tags():
_cout=1
tag_ui_back                    = _cout ; _cout = _cout + 1
tag_ui_timer_reset             = _cout ; _cout = _cout + 1
tag_ui_timer_start             = _cout ; _cout = _cout + 1
tag_ui_timer_split             = _cout ; _cout = _cout + 1
tag_ui_timer_pause             = _cout ; _cout = _cout + 1
tag_ui_lds_scan                = _cout ; _cout = _cout + 1
tag_ui_lds_data                = _cout ; _cout = _cout + 1
tag_ui_lds_info                = _cout ; _cout = _cout + 1
tag_ui_lds_info_back           = _cout ; _cout = _cout + 1
tag_ui_lds_home                = _cout ; _cout = _cout + 1
tag_ui_lds_back                = _cout ; _cout = _cout + 1
tag_ui_lds_reset_data          = _cout ; _cout = _cout + 1
tag_ui_lds_4in1_t              = _cout ; _cout = _cout + 1
tag_ui_lds_4in1_a              = _cout ; _cout = _cout + 1
tag_ui_lds_4in1_m              = _cout ; _cout = _cout + 1
tag_ui_lds_4in1_h              = _cout ; _cout = _cout + 1
tag_ui_lds_co2_t              = _cout ; _cout = _cout + 1
tag_ui_lds_co2_a              = _cout ; _cout = _cout + 1
tag_ui_lds_co2_co2              = _cout ; _cout = _cout + 1
tag_ui_lds_co2_h              = _cout ; _cout = _cout + 1
tag_ui_lds_data                = _cout ; _cout = _cout + 1
tag_ui_lds_data_0              = _cout ; _cout = _cout + 1
tag_ui_lds_data_1              = _cout ; _cout = _cout + 1
tag_ui_lds_data_2              = _cout ; _cout = _cout + 1
tag_ui_lds_data_3              = _cout ; _cout = _cout + 1
tag_ui_lds_data_4              = _cout ; _cout = _cout + 1
tag_ui_lds_data_5              = _cout ; _cout = _cout + 1
tag_ui_lds_relay_ch1           = _cout ; _cout = _cout + 1
tag_ui_lds_relay_ch2           = _cout ; _cout = _cout + 1
tag_ui_lds_data_text            = _cout ; _cout = _cout + 1
tag_ui_lds_data_gui            = _cout ; _cout = _cout + 1
