""" BridgeTek FT80X's definitions """
from .brt_eve_module import BrtEveModule
from .brt_eve_common import const

class BrtEve(BrtEveModule): # pylint: disable=too-few-public-methods
    """FT80X specific commands, options and registers"""

    # Macros related to inbuilt font
    #number of font characters per bitmap handle
    NUMCHAR_PERFONT            = const(128)

    #size of the font table - utilized for loopup by the graphics engine
    FONT_TABLE_SIZE            = const(148)

    #pointer to the inbuilt font tables starting from bitmap handle 16
    FONT_TABLE_POINTER         = const(0xFFFFC)

    # Synthesized sound macros
    SILENCE                    = const(0x00)
    SQUAREWAVE                 = const(0x01)
    SINEWAVE                   = const(0x02)
    SAWTOOTH                   = const(0x03)
    TRIANGLE                   = const(0x04)
    BEEPING                    = const(0x05)
    ALARM                      = const(0x06)
    WARBLE                     = const(0x07)
    CAROUSEL                   = const(0x08)

    # Synthesized sound frequencies, midi note macros
    MIDI_A0                    = const(21)
    MIDI_A_0                   = const(22)
    MIDI_B0                    = const(23)
    MIDI_C1                    = const(24)
    MIDI_C_1                   = const(25)
    MIDI_D1                    = const(26)
    MIDI_D_1                   = const(27)
    MIDI_E1                    = const(28)
    MIDI_F1                    = const(29)
    MIDI_F_1                   = const(30)
    MIDI_G1                    = const(31)
    MIDI_G_1                   = const(32)
    MIDI_A1                    = const(33)
    MIDI_A_1                   = const(34)
    MIDI_B1                    = const(35)
    MIDI_C2                    = const(36)
    MIDI_C_2                   = const(37)
    MIDI_D2                    = const(38)
    MIDI_D_2                   = const(39)
    MIDI_E2                    = const(40)
    MIDI_F2                    = const(41)
    MIDI_F_2                   = const(42)
    MIDI_G2                    = const(43)
    MIDI_G_2                   = const(44)
    MIDI_A2                    = const(45)
    MIDI_A_2                   = const(46)
    MIDI_B2                    = const(47)
    MIDI_C3                    = const(48)
    MIDI_C_3                   = const(49)
    MIDI_D3                    = const(50)
    MIDI_D_3                   = const(51)
    MIDI_E3                    = const(52)
    MIDI_F3                    = const(53)
    MIDI_F_3                   = const(54)
    MIDI_G3                    = const(55)
    MIDI_G_3                   = const(56)
    MIDI_A3                    = const(57)
    MIDI_A_3                   = const(58)
    MIDI_B3                    = const(59)
    MIDI_C4                    = const(60)
    MIDI_C_4                   = const(61)
    MIDI_D4                    = const(62)
    MIDI_D_4                   = const(63)
    MIDI_E4                    = const(64)
    MIDI_F4                    = const(65)
    MIDI_F_4                   = const(66)
    MIDI_G4                    = const(67)
    MIDI_G_4                   = const(68)
    MIDI_A4                    = const(69)
    MIDI_A_4                   = const(70)
    MIDI_B4                    = const(71)
    MIDI_C5                    = const(72)
    MIDI_C_5                   = const(73)
    MIDI_D5                    = const(74)
    MIDI_D_5                   = const(75)
    MIDI_E5                    = const(76)
    MIDI_F5                    = const(77)
    MIDI_F_5                   = const(78)
    MIDI_G5                    = const(79)
    MIDI_G_5                   = const(80)
    MIDI_A5                    = const(81)
    MIDI_A_5                   = const(82)
    MIDI_B5                    = const(83)
    MIDI_C6                    = const(84)
    MIDI_C_6                   = const(85)
    MIDI_D6                    = const(86)
    MIDI_D_6                   = const(87)
    MIDI_E6                    = const(88)
    MIDI_F6                    = const(89)
    MIDI_F_6                   = const(90)
    MIDI_G6                    = const(91)
    MIDI_G_6                   = const(92)
    MIDI_A6                    = const(93)
    MIDI_A_6                   = const(94)
    MIDI_B6                    = const(95)
    MIDI_C7                    = const(96)
    MIDI_C_7                   = const(97)
    MIDI_D7                    = const(98)
    MIDI_D_7                   = const(99)
    MIDI_E7                    = const(100)
    MIDI_F7                    = const(101)
    MIDI_F_7                   = const(102)
    MIDI_G7                    = const(103)
    MIDI_G_7                   = const(104)
    MIDI_A7                    = const(105)
    MIDI_A_7                   = const(106)
    MIDI_B7                    = const(107)
    MIDI_C8                    = const(108)

    # Maximum display display resolution supported by graphics engine
    MAX_DISPLAYWIDTH           = const(512)
    MAX_DISPLAYHEIGHT          = const(512)

    # Coprocessor reset related macros
    RESET_HOLD_COPROCESSOR     = const(1)
    RESET_RELEASE_COPROCESSOR  = const(0)

    # Macros for audio playback parameters
    AUDIO_SAMPLINGFREQ_MIN     = const(8 * 1000)
    AUDIO_SAMPLINGFREQ_MAX     = const(48 * 1000)

    # Memory Map
    RAM_G                      = const(0x000000)
    ROM_CHIPID                 = const(0x0C0000)
    ROM_FONT                   = const(0x0BB23C)
    ROM_FONT_ADDR              = const(0x0FFFFC)
    RAM_DL                     = const(0x100000)
    RAM_PAL                    = const(0x102000)
    RAM_REG                    = const(0x108000)
    RAM_CMD                    = const(0x108000)
    RAM_SCREENSHOT             = const(0x1C2000)

    # Memory buffer sizes
    RAM_G_SIZE                 = const(256 * 1024)
    ROM_CHIPID_SIZE            = const(4)
    ROM_FONT_SIZE              = const(275 * 1024)
    ROM_FONT_ADDR_SIZE         = const(4 * 1024)
    RAM_DL_SIZE                = const(8 * 1024)
    RAM_PAL_SIZE               = const(1 * 1024)
    RAM_REG_SIZE               = const(380)
    RAM_CMD_SIZE               = const(4 * 1024)
    RAM_SCREENSHOT             = const(2 * 1024)

    # Register definitions
    REG_CLOCK                  = const(0x102408)
    REG_CMD_DL                 = const(0x1024EC)
    REG_CMD_READ               = const(0x1024E4)
    REG_CMD_WRITE              = const(0x1024E8)
    REG_CPURESET               = const(0x10241C)
    REG_CSPREAD                = const(0x102464)
    REG_DITHER                 = const(0x10245C)
    REG_DLSWAP                 = const(0x102450)
    REG_FRAMES                 = const(0x102404)
    REG_FREQUENCY              = const(0x10240C)
    REG_GPIO                   = const(0x102490)
    REG_GPIO_DIR               = const(0x10248C)
    REG_HCYCLE                 = const(0x102428)
    REG_HOFFSET                = const(0x10242C)
    REG_HSIZE                  = const(0x102430)
    REG_HSYNC0                 = const(0x102434)
    REG_HSYNC1                 = const(0x102438)
    REG_ID                     = const(0x102400)
    REG_INT_EN                 = const(0x10249C)
    REG_INT_FLAGS              = const(0x102498)
    REG_INT_MASK               = const(0x1024A0)
    REG_MACRO_0                = const(0x1024C8)
    REG_MACRO_1                = const(0x1024CC)
    REG_OUTBITS                = const(0x102458)
    REG_PCLK                   = const(0x10246C)
    REG_PCLK_POL               = const(0x102468)
    REG_PLAY                   = const(0x102488)
    REG_PLAYBACK_FORMAT        = const(0x1024B4)
    REG_PLAYBACK_FREQ          = const(0x1024B0)
    REG_PLAYBACK_LENGTH        = const(0x1024A8)
    REG_PLAYBACK_LOOP          = const(0x1024B8)
    REG_PLAYBACK_PLAY          = const(0x1024BC)
    REG_PLAYBACK_READPTR       = const(0x1024AC)
    REG_PLAYBACK_START         = const(0x1024A4)
    REG_PWM_DUTY               = const(0x1024C4)
    REG_PWM_HZ                 = const(0x1024C0)
    REG_ROTATE                 = const(0x102454)
    REG_SCREENSHOT_BUSY        = const(0x1024D8)
    REG_SCREENSHOT_EN          = const(0x102410)
    REG_SCREENSHOT_READ        = const(0x102554)
    REG_SCREENSHOT_START       = const(0x102418)
    REG_SCREENSHOT_Y           = const(0x102414)
    REG_SOUND                  = const(0x102484)
    REG_SWIZZLE                = const(0x102460)
    REG_TAG                    = const(0x102478)
    REG_TAG_X                  = const(0x102470)
    REG_TAG_Y                  = const(0x102474)
    REG_TAP_CRC                = const(0x102420)
    REG_TAP_MASK               = const(0x102424)
    REG_TOUCH_ADC_MODE         = const(0x1024F4)
    REG_TOUCH_CHARGE           = const(0x1024F8)
    REG_TOUCH_DIRECT_XY        = const(0x102574)
    REG_TOUCH_DIRECT_Z1Z2      = const(0x102578)
    REG_TOUCH_MODE             = const(0x1024F0)
    REG_TOUCH_OVERSAMPLE       = const(0x102500)
    REG_TOUCH_RAW_XY           = const(0x102508)
    REG_TOUCH_RZ               = const(0x10250C)
    REG_TOUCH_RZTHRESH         = const(0x102504)
    REG_TOUCH_SCREEN_XY        = const(0x102510)
    REG_TOUCH_SETTLE           = const(0x1024FC)
    REG_TOUCH_TAG              = const(0x102518)
    REG_TOUCH_TAG_XY           = const(0x102514)
    REG_TOUCH_TRANSFORM_A      = const(0x10251C)
    REG_TOUCH_TRANSFORM_B      = const(0x102520)
    REG_TOUCH_TRANSFORM_C      = const(0x102524)
    REG_TOUCH_TRANSFORM_D      = const(0x102528)
    REG_TOUCH_TRANSFORM_E      = const(0x10252C)
    REG_TOUCH_TRANSFORM_F      = const(0x102530)
    REG_TRACKER                = const(0x109000)
    REG_TRIM                   = const(0x10256C)
    REG_VCYCLE                 = const(0x10243C)
    REG_VOFFSET                = const(0x102440)
    REG_VOL_PB                 = const(0x10247C)
    REG_VOL_SOUND              = const(0x102480)
    REG_VSIZE                  = const(0x102444)
    REG_VSYNC0                 = const(0x102448)
    REG_VSYNC1                 = const(0x10244C)

    def __init__(self, host):
        BrtEveModule.__init__(self)
        self.host = host
        self.eve = self
        self.eve_type = "ft80x"
